<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Platform Revenue Report</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #1f2937; margin: 32px; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        .meta { color: #6b7280; margin-bottom: 20px; }
        h2 { font-size: 14px; margin-top: 24px; margin-bottom: 8px; color: #374151; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { text-align: left; padding: 7px 10px; border-bottom: 1px solid #e5e7eb; }
        th { background: #f9fafb; font-weight: 600; }
        td.amount, th.amount { text-align: right; font-family: monospace; }
        td.right, th.right { text-align: right; }
        .total-row { font-weight: 700; background: #f3f4f6; }
        .summary-table th { width: 60%; }
        .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 9999px; font-size: 10px; font-weight: 600; background: #d1fae5; color: #065f46; }
    </style>
</head>
<body>
    <h1>Platform Revenue Report</h1>
    <div class="meta">
        Period: {{ $dateRange }}<br>
        Generated: {{ $generatedAt }}
    </div>

    <h2>Summary</h2>
    <table class="summary-table">
        <thead>
            <tr>
                <th>Metric</th>
                <th class="amount">Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total donations</td>
                <td class="amount">{{ number_format($summary['totalTransactions']) }}</td>
            </tr>
            <tr>
                <td>Donation volume</td>
                <td class="amount">MYR {{ number_format($summary['totalDonationVolume'], 2) }}</td>
            </tr>
            <tr>
                <td>Average donation size</td>
                <td class="amount">MYR {{ number_format($summary['averageDonationSize'], 2) }}</td>
            </tr>
            <tr>
                <td>Total Ihsan processing fees</td>
                <td class="amount">MYR {{ number_format($summary['totalProcessingFees'], 2) }}</td>
            </tr>
            <tr>
                <td>Average fee / transaction</td>
                <td class="amount">MYR {{ number_format($summary['averageFeePerTransaction'], 2) }}</td>
            </tr>
            <tr>
                <td>Effective fee rate</td>
                <td class="amount"><span class="badge">{{ number_format($summary['effectiveFeeRate'], 2) }}%</span></td>
            </tr>
        </tbody>
    </table>

    <h2>Revenue by Organization</h2>
    <table>
        <thead>
            <tr>
                <th>Organization</th>
                <th class="right">Public ID</th>
                <th class="right">Donations</th>
                <th class="amount">Volume</th>
                <th class="amount">Avg donation</th>
                <th class="amount">Stripe fees</th>
                <th class="amount">Processing fees</th>
                <th class="amount">Eff. rate</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    <td>{{ $row['name'] }}</td>
                    <td class="right">{{ $row['public_id'] }}</td>
                    <td class="right">{{ number_format($row['donations']) }}</td>
                    <td class="amount">MYR {{ $row['volume'] }}</td>
                    <td class="amount">{{ $row['avg_donation'] }}</td>
                    <td class="amount">{{ $row['stripe_fees'] }}</td>
                    <td class="amount">{{ $row['fees'] }}</td>
                    <td class="amount">{{ $row['effective_rate'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center; color: #9ca3af;">No revenue data for this period.</td>
                </tr>
            @endforelse
            @if (count($rows) > 0)
                <tr class="total-row">
                    <td>Total</td>
                    <td class="right"></td>
                    <td class="right">{{ number_format($totals['donations']) }}</td>
                    <td class="amount">MYR {{ number_format($totals['volume_raw'], 2) }}</td>
                    <td class="amount">MYR {{ number_format($totals['avg_donation_raw'], 2) }}</td>
                    <td class="amount">MYR {{ number_format($totals['stripe_fees_raw'], 2) }}</td>
                    <td class="amount">MYR {{ number_format($totals['fees_raw'], 2) }}</td>
                    <td class="amount">{{ number_format($totals['effective_rate_raw'], 2) }}%</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        Report generated by Ihsan platform.
    </div>
</body>
</html>
