<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Revenue Report — {{ $row['name'] }}</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #1f2937; margin: 40px; }
        h1 { font-size: 20px; margin-bottom: 6px; }
        .meta { color: #6b7280; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }
        th { background: #f9fafb; font-weight: 600; width: 60%; }
        .amount { text-align: right; font-family: monospace; }
        .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; }
    </style>
</head>
<body>
    <h1>Revenue Report</h1>
    <div class="meta">
        <strong>{{ $row['name'] }}</strong> ({{ $row['public_id'] }})<br>
        Period: {{ $period }} ({{ $dateRange }})<br>
        Generated: {{ $generatedAt }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Metric</th>
                <th class="amount">Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total donations</td>
                <td class="amount">{{ number_format($row['donations']) }}</td>
            </tr>
            <tr>
                <td>Donation volume</td>
                <td class="amount">MYR {{ number_format($row['volume_raw'], 2) }}</td>
            </tr>
            <tr>
                <td>Average donation size</td>
                <td class="amount">MYR {{ number_format($row['avg_donation_raw'], 2) }}</td>
            </tr>
            <tr>
                <td>Total Stripe fees</td>
                <td class="amount">MYR {{ number_format($row['stripe_fees_raw'], 2) }}</td>
            </tr>
            <tr>
                <td>Total Ihsan processing fees</td>
                <td class="amount">MYR {{ number_format($row['fees_raw'], 2) }}</td>
            </tr>
            <tr>
                <td>Effective fee rate</td>
                <td class="amount">{{ number_format($row['effective_rate_raw'], 2) }}%</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Report generated by Ihsan platform.
    </div>
</body>
</html>
