[program:ihsan-queue]
process_name=%(program_name)s_%(process_num)02d
command=/opt/homebrew/bin/php /Users/wmafendi/Herd/ihsan/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=wmafendi
numprocs=1
redirect_stderr=true
stdout_logfile=/Users/wmafendi/Herd/ihsan/storage/logs/queue-worker.log
stopwaitsecs=3600
